#!/bin/bash
TOEDIT="./czech.po"
CIL="./czechlanguage/"
PREFORMAT="UTF-8"
POSTFORMAT="iso-8859-2"
iconv -c --from utf8 --to ascii//TRANSLIT $TOEDIT > ${CIL}czech_ascii.po
# pridani radku 3 s hodnotou line 3
#sed '3iline 3' input.txt > output.txt
sed -i "s/$PREFORMAT/$POSTFORMAT/g" $CIL
echo "Prikaz proveden."

# pridani souboru czech.po do slozky k publikaci
cp czech.po $CIL
